### ISSUE TITLE
PKGbuild builds older version

### ISSUE THREAD

**Issue by Sukid** [manuel-192/remirror#2]
I prefer using this to Reflector, but whenever I went here or followed your instructions on the Antergos forums it kept giving me 1.49. I ended up adding your repo to my pacman anyway to get the latest one, but still, just thought I'd let you know.

**Comment by manuel-192** [comment]
Sorry about not responing earlier. This **remirror** is becoming obsolete, and I'm going to delete this remirror repo in the end of this year (2019). For now my **m-m** repo still has the remirror package, but I will not develop it anymore.

But instead you might be interested in this: under EndeavourOS (endeavouros.com) I made a GUI version of reflector called **reflector-simple**.
